#######
# Node Red Docker Compose
# mostly from https://nodered.org/docs/getting-started/docker
#######
services:
  node-red:
    build: .
    container_name: node-red-doug
    #image: nodered/node-red:latest
    entrypoint: npm node-red-doug run debug
    environment:
      - TZ=America/Detroit
    ports:
      - "1880:1880"
      - "9229:9229" # Debugging
    volumes:
      - ./data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
